# Site settings
title: ProjectBaseball.org
email: me@travisleleu.com
description: >
  Improve your baseball forecasting skill to improve your ability to predict player lines.  Get an edge in your fantasy league by more accurately predicting how a player will do.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://projectbaseball.org # the base hostname & protocol for your site
git_address: https://github.com/leleu/projectbaseball-org

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: spacelab

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: US/Los_Angeles
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"
- scope:
    path: _guts
    type: guts
  values:
    layout: page
    sectionid: guts
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
  guts:
    permalink: /guts/:path
    output: true
